# Generated by Django 4.2.5 on 2023-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_service_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
